spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://172.27.0.2:1124/dynamic_route?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最小，最大，初始化大小
      min-idle: 1
      max-active: 1
      initial-size: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 1
      max-pool-prepared-statement-per-connection-size: 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      show-sql: true
      format-sql: false
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      cache:
        use_second_level_cache: false
        use_query_cache: false
swagger:
  contact:
    name: SortfGrowingup
    url: http://www.alonexplore.com
    email: 199784567@qq.com
  enabled: true
  title: 小鹅通对接API
  version: 0.01
  description: 所有请求接口前面需要加'/xiaoe'
  base-path: /**
  base-package: com.nimblecloud.xiaoe.controller
  exclude-path: /error
